#
# Stupid simple makefile
#
all: build/ue
build/ue build:
	cc -o build/ue src/main.c

clean:
	rm -rf build/*

install:
	cp build/ue /usr/local/bin

debug/ue debug:
	mkdir -p debug
	cc -g -o build/ue src/main.c
